# Deployment Manifesto (k8s/deployment.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  # O Deployment cria e gerencia o ReplicaSet com 3 réplicas
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app-container
          image: basilioruan/aula-devops:0.1.0
          ports:
            - containerPort: 8080